### ISSUE TITLE
Headphone connection state not detected properly.

### ISSUE THREAD

**Issue by bamzoni** [voxeet/android-sdk-toolkit#3]
**Describe the bug**

Voxeet overlay fails to detect when headphones are plugged in/unplugged and keeps the state that was valid when starting the call so:
1. If headphones were connected before the call, speaker button is disabled.
2. if headphones weren't connected before the call, speaker button is working, even after connecting headphones.

Reproduced in sample app.

**Expected Behaviour**

Overlay should respond to headphones connected/disconnected events, and properly set speaker toggle button state.

**Steps to Reproduce the Problem**

  1. Start call with headphones connected to device
  2. Unplug headphones
  
**Specifications**

  - Device: Any (tested on Samsung Galaxy S8 & S7)
  - OS: Any (tested on 8.0 & 7.0)
  - Platform: Android
  - Version:
     - voxeetSdkVersion = "2.0.49.4" (also happening on earlier versions)

**Comment by codlab** [comment]
Fixed in 2.0.49.12 👍
