### ISSUE TITLE
Already in Call UI is closed when new calling user hangs up

### ISSUE THREAD

**Issue by vt-ombalakumar** [voxeet/android-sdk-toolkit#5]
**Describe the bug**
Ongoing Call UI is closed when another incoming call user has hung up or hung up automatically due to insufficient users

**Steps to Reproduce the Problem**

we have extended VoxeetIncomingCallActivity in a custom activity and set it to default incoming call activity and overridden on create Imethod
1st Scenario - when 2 users A and B are in the conference call, user C calls user A, call accept/reject UI is shown 

**Actual Requirement** 
Incoming call UI must not be shown when the conference is live)

Solution - To encounter this, we have added finish() in on create method in customIncomingCallActivity when the conference is live
            `if(VoxeetSdk.getInstance().conferenceService.isLive){
                this@CustomIncomingCallActivity.finish()
            }`
Now When user C calls user A, call accept/reject UI is not shown 

2nd Scenario
1. User A(Android) and User B(Android) both are available in a call 
2. User C(iOS) initiates a new call to user A
3. User A didn't get any notification for an incoming call from user C
4. User C waiting for 20 seconds and ended the call
5. As soon as User A Call UI closed but still, the conference is live?
I debugged and found that onConferenceDestroyPush is called when User C hangs up his call, Please see the reference image below, thanks
<img width="960" alt="todayCapture" src="https://user-images.githubusercontent.com/22934909/64907939-fae3db80-d716-11e9-97e8-362a134a9b6b.png">

**Specifications**

- Device: Any (tested on Nokia 7 Plus, Android Emulator (Custom Phone))
- OS: Any (tested on 9.0 & 8.0)
- Platform: Android
- Version:
       - voxeetSdkVersion = "2.0.49.18"

**Comment by codlab** [comment]
see 39179fbcb2eb945ed8ef3301d07969754beb7c50

**Comment by codlab** [comment]
How is your test going about this issue/fix?

**Comment by vt-ombalakumar** [comment]
Another Testing is going on, will get back on this issue once all testing is over, thanks

**Comment by vt-ombalakumar** [comment]
Tested this issue scenario too,  working fine now, so closing this issue
