### ISSUE TITLE
compiler issue after updating from master branch

### ISSUE THREAD

**Issue by vt-ombalakumar** [voxeet/android-sdk-toolkit#6]
**Describe the bug**

After merging our android sdk toolkit project with base master branch, we are getting compiler errors on ids

**Expected Behaviour**

compiler issues must not be there 

**Steps to Reproduce the Problem**

1. take update from master branch
2. click run app in android studio
3. compiler error occurs

<img width="960" alt="todayCapture1" src="https://user-images.githubusercontent.com/22934909/64909472-4653b500-d72a-11e9-9935-be990cd2011a.png">

**Comment by codlab** [comment]
you don't have a proper version of the repository

See the original repository : https://github.com/voxeet/android-sdk-toolkit/blob/master/toolkit/src/main/java/com/voxeet/toolkit/controllers/ReplayMessageToolkitController.java#L169

no trace of the issue you're having here. Make sure to update using the proper git command

**Comment by codlab** [comment]
for information, update made 12 days ago
