### ISSUE TITLE
Voxeet overlay freezes when web client joins conference.

### ISSUE THREAD

**Issue by bamzoni** [voxeet/android-sdk-toolkit#7]
**Describe the bug**

Overlay ui freezes, when android client is first one to join a conference, and then is followed by a web client. When the overlay is frozen, device continues to stream video and audio just fine, but UI is totally unresponsive, and the only way to fix that is killing the app. Following problem does not occur when android device is joining conference after web client.  Attached exception log. 

Unfortunately couldn't reproduce this in sample app, due to not being able to connect between web sample and android sample.

**Specifications**

  - Device: Tested on Galaxy S8 and S7
  - OS: 9.0, 8.0
  - Platform: Android
  - Version:
    - com.voxeet.sdk:toolkit:2.0.69.5

**Comment by codlab** [comment]
No logs attached.

**Comment by bamzoni** [comment]
[error.txt](https://github.com/voxeet/android-sdk-toolkit/files/3626225/error.txt)

**Comment by bamzoni** [comment]
[error_log.txt](https://github.com/voxeet/android-sdk-toolkit/files/3626248/error_log.txt)

**Comment by codlab** [comment]
The infinite looping event execution should be fixed using the latest 2.0.69.8 version of the toolkit

**Comment by bamzoni** [comment]
That fixed it. Thanks
