### ISSUE TITLE
2 Users accepts and rejects the call at the same time, creates new call in the accepted user device

### ISSUE THREAD

**Issue by vt-ombalakumar** [voxeet/android-sdk-toolkit#9]
**Describe the bug**
When 2 users accept and reject the call at the same time, a new call is started in the accepted user device

**Steps to Reproduce the Problem**
1. 2 Users are there in different phones User1(Android) and User2(iOS)
2. User2 starts a call to User1
3. User1 picks the call and User2 declines the call at the **same time**
4. however User1 starts a new ongoing call screen

**Actual Requirement** 
When 2 users accept and reject the call at the same time, accepting user must not start a new call

**Specifications**
- Device: Any (tested on Nokia 7 Plus, Android Emulator (Custom Phone) & iPhone X)
- OS: Android (tested on 9.0 & 8.0) iOS ( tested on iOS 12 )
- Platform: Android & iOS
- Version:
       - voxeetSdkVersion = "2.0.49.18"

**Comment by codlab** [comment]
_at the same time_ the flow implies a choice to be done. It must be managed afterwards on your side using the various event of participants

**Comment by codlab** [comment]
Another possibility, if using the sample for the toolkit, notice the MainActivity is by default creating invite call for users when accepting a call. Hence, any invited user will invite others => the caller (here iOS) will be invited even if a left

**Comment by vt-ombalakumar** [comment]
@codlab we have seen conferenceDestroyedPush event is called with event status - "MISSED" when 2 users accept or cancel the call at the same time

**Comment by vtkumaresan** [comment]
can we get specific event detail and document link to handle this scenario.
or this is an expected scenario?

**Comment by codlab** [comment]
The above comment gives the one event to use about this 👍
